### YamlMime:QSharpNamespace
uid: microsoft.quantum.environment
name: Microsoft 量子. 环境
summary: " # <a name=\"summary\"></a>总结\n 这些函数提供有关在其中发生量程计算的环境的信息。"
operations:
- uid: microsoft.quantum.environment.getqubitsavailabletoborrow
  summary: >-
    返回当前可用于借用的 qubits 的数目。

    这包括未使用的 qubits;也就是说，这包括 `GetQubitsAvailableToUse`返回的 qubits。
- uid: microsoft.quantum.environment.getqubitsavailabletouse
  summary: 返回当前可供使用的 qubits 的数目。
ms.openlocfilehash: 50e5cfb7c1b9a4075c25b2705d00b435a09e159e
ms.sourcegitcommit: 8becfb03eb60ba205c670a634ff4daa8071bcd06
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/30/2019
ms.locfileid: "73056834"
